brokers:
  - scheduler: lottery
    host: "localhost:11300"
    workertype: cmd
    workerendpoint: 
      - "/bin/bash"
      - "-c"
      - "source /home/vantt/bash_vantt; cd /ext4Data1/vantt/projects/php/anpha/mio/code; php bin/console.php --no-debug mio:task-handler"
    concurrent: 10
    queues:    
      - priority: 300
        queuenames: 
          - "default1"          
      - priority: 100
        queuenames: 
          - "default2"
      - priority: 50
        queuenames:           
          - "others"   
                       
  - scheduler: lottery
    host: "beanstalkd:11300"
    workertype: fastcgi
    workerendpoint:       
      - "/bin/bash"
      - "-c"
      - "cat "
    concurrent: 20
    queues:    
      - priority: 300
        queuenames: 
          - "default1"          
      - priority: 100
        queuenames: 
          - "default2"
          - "others" 
      - priority: 50
        queuenames:           
          - "others"      