brokers:
  - scheduler: lottery
    host: "localhost:11300"
    workertype: cmd
    workerendpoint: "cat"
    concurrent: 10
    queues:    
      - priority: 300
        queuenames: 
          - "default1"          
      - priority: 100
        queuenames: 
          - "default2"
      - priority: 50
        queuenames:           
          - "others"                
  - scheduler: lottery
    host: "52.221.223.247:11300"
    workertype: fastcgi
    workerendpoint: "php bin/console.php exec"
    concurrent: 20
    queues:    
      - priority: 300
        queuenames: 
          - "default1"          
      - priority: 100
        queuenames: 
          - "default2"
          - "others" 
      - priority: 50
        queuenames:           
          - "others"      